name: ADMX-MSI-SETUP

on: [ push, pull_request ]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    name: Check shell script syntax with shellcheck
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: sudo apt-get install shellcheck
      - run: shellcheck *.sh
  build:
    runs-on: ubuntu-latest
    name: Build software using docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: docker build . --file Dockerfile --tag build-environment
      - run: docker run -i --log-driver=none -a stdin -a stdout -a stderr -v "$(pwd)":/app build-environment
